main/urls.py
from django.urls import path
from .import views

app_name = "main"

urlpatterns = [
path('', views.home, name="home"),
path('details/<int:id>/', views.detail, name="detail"),
path('addmovies/', views.add_movies, name="add_movies"),
path('editmovies/<int:id>/', views.edit_movies, name="edit_movies"),
path('deletemovies/<int:id>/', views.delete_movies, name="delete_movie"),
path('addreview/<int:id>/', views.add_review, name="add_review")
    ]

moviereview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.url')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Movie(models.Model):
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=300)
    cast = models.CharField(max_length=800)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    averageRating = models.FloatField()
    image = models.URLField(default=None, null=True)

    def _str_(self):
        return self.name
    
    def __unicode__(self):
        return self.name
    
class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username


    

models.py
from django.db import models

# Create your models here.

forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

main/forms.py
from django import forms
from .models import *



class MovieForm(forms.ModelForm):
    class Meta:
        Movie = models
        fields = ('name', 'director', 'text', 'description', 'release_date', 'image')

class ReviewForm(forms.ModelForm):
    class Meta:
        Review = models
        fields = ("comment", "rating")
      

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
# Create your views here.

def home(request):
   query = request.GET.get("title")
   allMovies = None
   if query:
      allMovies = Movie.objects.filter(name_icontains=query)
   else:
      allMovies = Movie.objects.all()

   context = {
      "movies": allMovies,
   }
   
   return render(request, 'main/index.html', context)

def detail(request, id):
   movie = Movie.objects.get(id=id)
   reviews = Review.objects.filter(movie=id).order_by("-comment")

   context = {
      "movie": movie,
      "reviews": reviews
   }
   return render(request, 'main/details.html', context)

def add_movies(request):
   if request.user.is_authenticated:
      if request.user.is_superuser:
         if request.method == "POST":
            form = MovieForm(request.POST or None)

            if form.is_valid():
               data = form.save(commit=False)
               data.save()
            return redirect("main:home")
         else:
            form = MovieForm()
         return render(request, 'main/addmovies.html', {"form": form,  "controller": "Add Movies"})
      
      else:
         return redirect("main:home")
   return redirect("accounts:login")

def edit_movies(request, id):
   if request.user.is_authenticated:
      if request.user.is_superuser:

            movie = Movie.objects.get(id=id)
   
            if request.method == "POST":
               form = MovieForm(request.POST or None, instance=movie)

               if form.is_vaild():
                  data = form.save(commit=False)
                  data.save()
                  return redirect ("main:detail", id)
            else:
               form = MovieForm(instance=movie)
            return render(request, 'main/addmovies.html', {"form": form, "controllor": "Edit Movies" })
      
      else:
         return redirect("main:home")
   return redirect("accounts:login")
   
def delete_movies(request, id):
   if request.user.is_authenticated:
      if request.user.is_superuser:
         movie = Movie.objects.get(id=id)
         movie.delete()
         return redirect ("main:home")
      
      else:
         return redirect("main:home")
   return redirect("accounts:login")


def add_review(request, id):
   if request.user.is_authenticated:
      movie = Movie.object.get(id=id)
      if request.method == "POST":
         form = ReviewForm(request.POST or None)
         if form.is_vaild():
            data = form.save(commit=False)
            data.comment = request.POST["comment"]
            data.rating = request.POST["rating"]
            data.user = request.user
            data.movie = movie
            data.save()
            return redirect("main:detail", id)
      else:
         form = ReviewForm()
      return render(request, 'main/details.html', {"form":form })
   else:
      return redirect("accounts:login")
   

   

views.py
from django.shortcuts import redirect, render
from .forms import *
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def register(request):
    if request.user.is_authenticated:
        return redirect("main:home")
    
    else:
        if request.method == "POST":
           form = RegistrationForm(request.POST or None)
        
           if form.is_valid():
               user = form.save()

               raw_password = form.cleaned_data.get('password1')

               user = authenticate(username=user.username, password=raw_password)

               login(request, user)

               return redirect('main:home')
        
        else:
            form = RegistrationForm()
        return render(request, "accounts/register.html", {"form" : form})

def login_user(request):
    if request.user.is_authenticated:
       return redirect("main:home")
    
    else:
        if request.method == "POST":
           username =  request.POST['username']
           password = request.POST['password']

           print(username, password)

           user = authenticate(username=username, password=password)
        
           if user is not None:
              if user.is_active:
                 login(request, user)
                 return redirect("main:home")
              else: 
                 return render(request, 'accounts/login.html', {"error": "Your account has been disabled."})
           else: 
               return render(request, 'accounts/login.html', {"error": "Invaid Username or Password."})
        return render(request, 'account/login.html')

def logout_user(request):
    if request.user.is_authenticated:
       logout(request)
       print("logged out succesfully")
       return redirect("accounts:login")
    else:
        return redirect("accounts:login")

main/templates/main/addmovies.html
{% extends 'main.base.html' %}

{% load crispy_form_tags %}

{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                (( form | crispy ))
                <input type="submit" value="{{ controller }}" class="btn btn-danger">
            </form>
            
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>Movie Reviews</title>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand" href="(% url 'main:home' %)">Movie Reviews</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="(% url 'main:home' %)">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="(% url 'main:add_movies' %)">Add Movies</a>
            </li>
            {% if user.is_authenticaated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">My profile</a>

                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
              </div>
            </li>
            {% else %}
          <li class="nav-item">
            <a class="nav-link" href="(% url 'accounts:login' %)">Login</a>
          <li class="nav-item">
            <a class="nav-link" href="(% url 'accounts:logout' %)">Logout</a>
            {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'main:home' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
      
      <h1>Welcome to the website!</h1>

    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ movie.image }}" alt="{{ movie.name }}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h3 class="text-center">
                    {{ movie.name }}
                </h3>
                <p>{{ movie.description }}</p>
                <h5>Director: {{ movie.director }}</h5>
                <h5>Cast: {{ movie.cast }}</h5>
                <h5>Rating: {{ movie.averageRating}}</h5>

                {% if request.user.is_authenticated %}
                   {% if request.user.is_superuser %}
                <a href="{% url 'main:edit_movies' movie.id %}" class="btn btn-warning">Edit Movie</a>
                <a href="{% url 'main:delete_movie' movie.id %}" class="btn btn-danger">Delete Movie</a>
                   {% endif %}
                {% endif %}
            </div>
        </div>
        </div>
    </div>
</div>

<br>
    <div class="card">
        <div class="card-body">
                <h3 class="text-center">Add Review</h3>
                <form action="{% url 'main:add_review' movie.id %}" method="POST">
                    {% csrf_token %}
                    <label for="comment">Review</label>
                    <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>

                    <label for="rating">Rating</label>
                    <input type="text" name="rating" class="form-control">

                    <br>
                    <input type="submit" class="btn btn-danger" value="Add Review">
                </form> 
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% for review in reviews %}
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <h5 class="text-left">{{ review.user.username }}</h5>
                            <h5>{{ review.rating }}</h5>
                        </div>
                        <div class="col-md-9">
                            <p>{{ review.rating }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for movie in movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                            <img src="{{ movie.image }}" alt="" class="img-fluid" width="75%">
                            <h3 class="text-center">{{movie.name}}</h3>
                                <i class="text-center">{{ movie.release_date }}</i>
                                <a href="{% url 'main:detail' movie.id %}">Read More</a>
                            </div>
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/register.html
{% extends 'main/base.html %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="card">
        <div class="card-body">
                <h3 class="text-center">Register and Account</h3>
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="Register" class="btn btn-danger">
        </div>
    </div>
</div>


templates/login.html
{% extends 'main/base.html %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
                <h3 class="text-center">Login in your account</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    <label for="username">Username</label>
                    <input type="text" placeholder="Enter your username" class="form-control" name="Username">

                    <label for="password">Password</label>
                    <input type="password" placeholder="Enter your password" class="form-control" name="Password">
                    <br>
                    {% if error %}
                        <i style="color:red">{{ error }}</i>
                    {% endif %}
                    ><input type="sunmit" value="Login" class="btn btn-danger">
                </form>
        </div>
    </div>
</div>

{% endblock %}